DACS/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DACS.Models;
using PagedList.Mvc;
using PagedList;

namespace DACS.Controllers
{
    public class SanPhamController : Controller
    {
        dbQuanLyBanGiayDataContext db = new dbQuanLyBanGiayDataContext();
        // GET: SanPham
        public ActionResult SanPham()
        {
            var s = from ss in db.Giays select ss;
            return View(s);
        }

        public ActionResult Details(int id)
        {
            var details = db.Giays.Where(s => s.MaSP == id).First();
            return View(details);
        }

        public ActionResult ListSize(int id)
        {
            ViewBag.Size = new SelectList(db.SizeGiays.ToList().OrderBy(n => n.Size).Where(n => n.MaSP == id), "Size", "Size");

            var size = from ss in db.SizeGiays where ss.MaSP == id select ss;
            return View(size);
        }

        public ActionResult ThuongHieu()
        {
            var th = from tn in db.ThuongHieus select tn;
            return PartialView(th);
        }
        public ActionResult GiayTheoTH(int id)
        {
            var th = from ss in db.Giays where id == ss.MaTH select ss;
            return View(th);
        }
        //public ActionResult SanPham(int? page)
        //{
        //    int pageSize = 8;
        //    int pageNum = (page ?? 1);
        //    var sanphammoi = Listgiaymoi(100);
        //    return View(sanphammoi.ToPagedList(pageNum, pageSize));
        //}
        //private List<Giay> Listgiaymoi(int count)
        //{
        //    return db.Giays.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        //}

    }
}

DACS/Views/SanPham/Details.cshtml
@model DACS.Models.Giay
@using DACS.Models
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="colorlib-loader"></div>
<div id="page">
    <div class="breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col">
                    <p class="bread"><span><a href="index.html">Trang Chủ</a></span> / <span>Chi Tiết Sản Phẩm</span></p>
                </div>
            </div>
        </div>
    </div>
    @using (Html.BeginForm("ThemGioHang", "GioHang", new { @iMaSP = @Model.MaSP, @strURL = Request.Url.ToString() }, FormMethod.Post))
    {
        <div class="colorlib-product">
            <div class="container">
                <div class="row row-pb-lg product-detail-wrap">
                    <div class="col-sm-8">
                        <div class="item">
                            <div class="product-entry border">
                                <a href="#" class="prod-img">
                                    <img src="~/images/@Model.HinhAnh" class="img-fluid" alt="#">
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="product-desc">
                            <h3>@Model.TenSP</h3>
                            <p class="price">
                                <span>@string.Format("{0:0,0}", Model.GiaBan) VNĐ</span>
                            </p>
                            <p>@Model.Mota</p>
                            @Html.Action("ListSize", "SanPham")
                            <div class="input-group mb-4">
                                <span class="input-group-btn">
                                    <button type="button" class="quantity-left-minus btn" data-type="minus" data-field="">
                                        <i class="icon-minus2"></i>
                                    </button>
                                </span>
                                <input type="text" id="quantity" name="txtSoluong" class="form-control input-number" value="1" min="1" max="100">
                                <span class="input-group-btn ml-1">
                                    <button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">
                                        <i class="icon-plus2"></i>
                                    </button>
                                </span>
                                <script src="~/Scripts/main.js"></script>
                                <script>
                                    $(document).ready(function () {
                                        var quantitiy = 0;
                                        $('.quantity-right-plus').click(function (e) {
                                            // Stop acting like a button
                                            e.preventDefault();
                                            // Get the field name
                                            var quantity = parseInt($('#quantity').val());
                                            // If is not undefined
                                            $('#quantity').val(quantity + 1);
                                            // Increment
                                        });
                                        $('.quantity-left-minus').click(function (e) {
                                            // Stop acting like a button
                                            e.preventDefault();
                                            // Get the field name
                                            var quantity = parseInt($('#quantity').val());
                                            // If is not undefined
                                            // Increment
                                            if (quantity > 0) {
                                                $('#quantity').val(quantity - 1);
                                            }
                                        });
                                    });
                                </script>
                            </div>
                            @*<div class="row">
                                    <div class="col-sm-12 text-center">
                                        <p class="addtocart">
                                            <a href="@Url.Action("ThemGioHang", "GioHang", new { @iMaSP = @Model.MaSP,@strURL=Request.Url.ToString() })" class="btn btn-primary btn-addtocart"><i class="icon-shopping-cart"></i> Thêm Vào Giỏ</a>

                                        </p>
                                    </div>
                                </div>*@
                            <button type="submit" class="btn" style="padding:10px 15px">
                                <i class="icon-shopping-cart" style="font-size:20px"> <span style="font-size:20px">Thêm Vào Giỏ</span></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

DACS/Views/SanPham/GiayTheoTH.cshtml
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="colorlib-product">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 offset-sm-2 text-center colorlib-heading">
            </div>
        </div>
        <div class="row row-pb-md">
            @foreach (var item in Model)
            {
                <div class="col-lg-3 mb-4 text-center">
                    <div class="product-entry border">
                        <a href="@Url.Action("Details","SanPham", new { id = @item.MaSP })" class="prod-img">
                            <img src="~/images/@item.HinhAnh" class="img-fluid" alt="Free html5 bootstrap 4 template">
                        </a>
                        <div class="desc">
                            <h2><a href="@Url.Action("Details","SanPham", new { id = @item.MaSP })">@item.TenSP</a></h2>
                            <span class="price">@string.Format("{0:0,0}", item.GiaBan) VNĐ</span>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

DACS/Views/SanPham/ListSize.cshtml
@model IEnumerable<DACS.Models.SizeGiay>
@{
    Layout = null;
}

<div class="row">
        <ul class="form-control-lg dropdown-toggle-split">
            Size:  @Html.DropDownList("Size")
        </ul>   
</div>

DACS/Views/SanPham/SanPham.cshtml
@model IEnumerable<DACS.Models.Giay>
@{ Layout = null;}

<div class="colorlib-product">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 offset-sm-2 text-center colorlib-heading">
                
            </div>
        </div>
        <div class="row row-pb-md">
            @foreach(var item in Model)
            { 
            <div class="col-lg-3 mb-4 text-center">
                <div class="product-entry border">
                    <a href="@Url.Action("Details","SanPham", new { id = @item.MaSP })" class="prod-img">
                        <img src="~/images/@item.HinhAnh" class="img-fluid" alt="Free html5 bootstrap 4 template">
                    </a>
                    <div class="desc">
                        <h2><a href="@Url.Action("Details","SanPham", new { id = @item.MaSP })">@item.TenSP</a></h2>
                        <span class="price">@string.Format("{0:0,0}", item.GiaBan) VNĐ</span>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

DACS/Views/SanPham/ThuongHieu.cshtml
    @foreach (var item in Model)
    {
        <li style="color:white">
            @*<a href="@Url.Action("GiayTheoTH", "SanPham","SanPham", new { id = item.MaTH})" class="list-group-item">
                @item.TenTH
            </a>*@
            <a href="/SanPham/GiayTheoTH/@item.MaTH">@item.TenTH</a>
        </li>
    }