DACS/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DACS.Models;
using System.Web.Mvc;

namespace DACS.Controllers
{
    public class NguoiDungController : Controller
    {
        dbQuanLyBanGiayDataContext db = new dbQuanLyBanGiayDataContext();
        // GET: NguoiDung
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection collect, KhachHang kh)
        {
            var hoten = collect["HoTen"];
            var tendn = collect["Taikhoan"];
            var matkhau = collect["Matkhau"];
            var matkhaunhaplai = collect["matkhaukhnhaplai"];
            var diachi = collect["DiaChi"];
            var gioitinh = collect["GioiTinh"]; 
            var email = collect["Email"];
            var dienthoai = collect["DienThoai"];
            var ngaysinh = string.Format("{0:mm/dd/yyyy}", collect["ngaysinh"]);
            int lenght = matkhau.Length;
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được bỏ trống !";
            }
            else
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Tên đăng nhập không được bỏ trống !";
            }
            else
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Mật khẩu không được bỏ trống !";
            }
            else if(lenght<6)
            {
                ViewData["Loilenght"] = "Mật khẩu phải từ 6 ký tự trở lên !";
            }
            else
            if (String.IsNullOrEmpty(matkhaunhaplai) || matkhau.ToString() != matkhaunhaplai.ToString())
            {
                ViewData["Loi4"] = "Mật khẩu nhập lại sai!";
            }
            else
            if (String.IsNullOrEmpty(diachi))
            {
                ViewData["Loi5"] = "Địa chi khách hàng không được bỏ trống !";
            }
            else
            if(String.IsNullOrEmpty(gioitinh))
            {
                ViewData["Loi6"] = "Giới tính khánh hàng không được bỏ trống !";
            }
            else
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi7"] = "Email khách hàng không được bỏ trống !";
            }
            else
            if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi8"] = "Điện thoại khách hàng không được bỏ trống !";
            }
            else
            if (String.IsNullOrEmpty(ngaysinh))
            {
                ViewData["Loi9"] = "Ngày sinh khách hàng không được bỏ trống !";
            }
            else
            {
                kh.HoTen = hoten;
                kh.Taikhoan = tendn;
                kh.Matkhau = matkhau;
                kh.DiaChi = diachi;
                kh.GioiTinh = gioitinh;
                kh.Email = email;
                kh.DienThoai = dienthoai;
                kh.NgaySinh = DateTime.Parse(ngaysinh);
                db.KhachHangs.InsertOnSubmit(kh);
                db.SubmitChanges();
                return RedirectToAction("DangNhap");
            }
            return this.DangKy();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            var tendn = collection["Taikhoan"];
            var matkhau = collection["Matkhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
               KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.Taikhoan == tendn && n.Matkhau == matkhau);
                if (kh != null)
                {
                    ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";
                    Session["Taikhoankh"] = kh;
                    Session["Tentkh"] = collection["Taikhoan"].ToString();
                    Session["tendn"] = tendn.ToString();
                    return RedirectToAction("Index", "Home");
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
        public ActionResult DangXuat()
        {
            Session["Taikhoankh"] = null;
            
            Session["GioHang"] = null;
            return RedirectToAction("Index", "Home");
        }
        
    }
}

DACS/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <title> @ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rokkitt:100,300,400,700" rel="stylesheet">
    <style>
        .dropbtn {
            background-color: white;
            color: black;
            padding: 16px;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

                .dropdown-content a:hover {
                    background-color: #f1f1f1;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {
            background-color: #f1f1f1;
        }
    </style>

    <link href="~/Content/NguoiDungCSS/NguoiDungCSS.css" rel="stylesheet" />
    <!-- Animate.css -->
    <link href="~/Content/animate.css" rel="stylesheet" />
    <!-- Icomoon Icon Fonts-->
    <link href="~/Content/icomoon.css" rel="stylesheet" />
    <!-- Ion Icon Fonts-->
    <link href="~/Content/ionicons.min.css" rel="stylesheet" />
    <!-- Bootstrap  -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Magnific Popup -->
    <link href="~/Content/magnific-popup.css" rel="stylesheet" />
    <!-- Flexslider  -->
    <link href="~/Content/flexslider.css" rel="stylesheet" />
    <!-- Owl Carousel -->
    <link href="~/Content/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Content/owl.theme.default.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!-- Date Picker -->
    <link href="~/Content/bootstrap-datepicker.css" rel="stylesheet" />
    <!-- Flaticons  -->
    <link href="~/fonts/flaticon/font/flaticon.css" rel="stylesheet" />
    <!-- Theme style  -->
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Scripts/main.js"></script>
    
</head>
<body>
    <nav class="colorlib-nav" role="navigation">
        <div class="container">
            <div class="row m-0" style="justify-content:space-between">
                <div>
                    <i class="fas fa-phone-volume"></i>
                    (09) 49 601714
                </div>
                <div class="DangKyDangNhap">
                    @if (Session["Taikhoankh"] == null || Session["Taikhoankh"].ToString() == "")
                    {
                        
                    }
                    else
                    {

                        <div class="dropdown">
                            <i class="dropbtn">Hello,@Session["Tentkh"]</i>
                            <div class="dropdown-content">
                                <a href="@Url.Action("Dangxuat","NguoiDung")">Log Out</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
                
    </nav>

    
    <div class="colorlib-partner">
        <div class="container">
            @RenderBody()
            
        </div>
    </div>
    
    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="ion-ios-arrow-up"></i></a>
    </div>

    <!-- jQuery -->
    <script src="~/Scripts/jquery.min.js"></script>
    <!-- popper -->
    <script src="~/Scripts/popper.min.js"></script>
    <!-- bootstrap 4.1 -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- jQuery easing -->
    <script src="~/Scripts/jquery.easing.1.3.js"></script>
    <!-- Waypoints -->
    <script src="~/Scripts/jquery.waypoints.min.js"></script>
    <!-- Flexslider -->
    <script src="~/Scripts/jquery.flexslider-min.js"></script>
    <!-- Owl carousel -->
    <script src="~/Scripts/owl.carousel.min.js"></script>
    <!-- Magnific Popup -->
    <script src="~/Scripts/jquery.magnific-popup.min.js"></script>
    <script src="~/Scripts/magnific-popup-options.js"></script>
    <!-- Date Picker -->
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <!-- Stellar Parallax -->
    <script src="~/Scripts/jquery.stellar.min.js"></script>
    <!-- Main -->
    <script src="~/Scripts/main.js"></script>
    
</body>
</html>